version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: proyecto0-postgres-local
    environment:
      POSTGRES_DB: proyecto_0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      # Mount the SQL scripts to initialize the database
      - ./db/000_create_tables.sql:/docker-entrypoint-initdb.d/001_project_tables.sql
      - ./db/001_data_dummy.sql:/docker-entrypoint-initdb.d/002_dummy_data.sql
      # Persist data in local volume
      - postgres_local_data:/var/lib/postgresql/data
    networks:
      - proyecto0-local-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proyecto_0"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto0-api-local
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      - DB_DRIVER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=proyecto_0
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SSL_MODE=disable
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=5

      # Server configuration
      - PORT=8080
      - HOST=0.0.0.0
      - GIN_MODE=debug

      # JWT configuration
      - JWT_SECRET=local-development-secret-key
      - JWT_ISSUER=Proyecto_0
      - JWT_EXPIRATION=24h

      # App configuration
      - APP_NAME=Proyecto_0
      - APP_VERSION=1.0.0
      - APP_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proyecto0-local-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto0-frontend-local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_local_modules:/app/node_modules
    depends_on:
      - api
      - postgres
    networks:
      - proyecto0-local-network
    restart: unless-stopped

volumes:
  postgres_local_data:
    driver: local

networks:
  proyecto0-local-network:
    driver: bridge
